title: PW-An Online Education Platform Portfolio
description: Online education platforms has been enhancing its services for quality education. This portfolio explores and analyses the functionalities provided by PW education platform along with the algorithms used to implement the respective funtionalities.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

